# Supabase configuration for hosted deployment
project_id = "pnoxqzlxfuvjvufdjuqh"

[auth]
enabled = true
site_url = "http://localhost:3001"
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false